# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.3-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # build the website
      - run: yarn build
      # run formatter
      - run: yarn prettier
      # run linter
      - run: yarn stylelint
      - run: yarn lint
      # run tests!
      - run: yarn test
      # install lighthouse-ci
      - run: sudo npm install -g @lhci/cli@0.3.x
      # run lighthouse analysis
      - run: lhci autorun
