backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Resume"
    name: "resume"
    files:
      - label: "Work experience"
        name: "work-experience"
        file: "content/resume/work-experience/work-experience.json"
        fields:
          - label: "Work experience"
            name: "work-experience"
            widget: "list"
            fields:
              - { label: "Start date", name: "startDate", widget: "string" }
              - { label: "End date", name: "endDate", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
      - label: "Education"
        name: "education"
        file: "content/resume/education/education.json"
        fields:
          - label: "Titles"
            name: "titles"
            widget: "list"
            fields:
              - { label: "End date", name: "endDate", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
      - label: "Languages"
        name: "languages"
        file: "content/resume/languages/languages.json"
        fields:
          - label: "Languages"
            name: "languages"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
